Наседкин Михаил
MichaelNN00001/JavaSchool pull request #1
Opened 2024-12-26 09:57 UTC by MichaelNN00001

ДЗ №1

2024-12-27 21:17 UTC, Liman26 requested changes

2024-12-27 21:17 UTC, Liman26 commented on src/main/java/sbp/school/kafka/service/ProducerService.java
> +            producer.flush();
Продюсер надо тоже закрывать

2024-12-27 21:17 UTC, Liman26 commented on src/main/java/sbp/school/kafka/util/ProducerPartitioner.java
> +//    private final static Map<String, Integer> PARTITIONS = Arrays
В ПР не должно быть закомментированного кода

2024-12-28 10:34 UTC, MichaelNN00001 commented on src/main/java/sbp/school/kafka/util/ProducerPartitioner.java
> +//    private final static Map<String, Integer> PARTITIONS = Arrays
Исправлено

2024-12-28 10:35 UTC, MichaelNN00001 commented on src/main/java/sbp/school/kafka/service/ProducerService.java
> +            producer.flush();
Исправлено

2025-01-21 04:31 UTC, Liman26 approved these changes
Исправления в один коммит

2025-01-21 14:36 UTC, merged